# Generated by Django 6.0.5 on 2026-06-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tvdb_id",
                    models.IntegerField(unique=True, verbose_name="آیدی تی وی دی بی"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام ژانر")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="اسلاگ"),
                ),
            ],
            options={
                "verbose_name": "ژانر",
                "verbose_name_plural": "ژانر ها",
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tvdb_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="آیدی تی وی دی بی"
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="نام شخص")),
                (
                    "image",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="تصویر"
                    ),
                ),
            ],
            options={
                "verbose_name": "شخص",
                "verbose_name_plural": "اشخاص",
                "db_table": "people",
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tvdb_id",
                    models.IntegerField(
                        db_index=True,
                        editable=False,
                        unique=True,
                        verbose_name="آیدی تی وی دی بی",
                    ),
                ),
                (
                    "schema_version",
                    models.IntegerField(default=1, editable=False, verbose_name="ورژن"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="نام سریال")),
                (
                    "slug",
                    models.SlugField(max_length=500, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "image",
                    models.URLField(blank=True, max_length=1000, verbose_name="تصویر"),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="سال ساخت"
                    ),
                ),
                ("overview", models.TextField(blank=True, verbose_name="خلاصه داستان")),
                (
                    "original_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کشور سازنده"
                    ),
                ),
                (
                    "original_language",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="زبان اصلی"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=50, verbose_name="وضعیت"),
                ),
                (
                    "episode_count",
                    models.IntegerField(default=0, verbose_name="تعداد قسمت\u200cها"),
                ),
                (
                    "season_count",
                    models.IntegerField(default=0, verbose_name="تعداد فصل\u200cها"),
                ),
                (
                    "rate",
                    models.FloatField(blank=True, null=True, verbose_name="امتیاز"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "overview_en",
                    models.TextField(blank=True, verbose_name="خلاصه داستان انگلیسی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "name_fa",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="نام فارسی"
                    ),
                ),
            ],
            options={
                "verbose_name": "سریال",
                "verbose_name_plural": "سریال ها",
                "db_table": "series",
            },
        ),
        migrations.CreateModel(
            name="RemoteId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(max_length=200, verbose_name="ریموت آیدی"),
                ),
                ("id_type", models.IntegerField(verbose_name="نوع آیدی")),
                (
                    "source_name",
                    models.CharField(max_length=100, verbose_name="نام منبع"),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_ids",
                        to="series.series",
                        verbose_name="سریال",
                    ),
                ),
            ],
            options={
                "verbose_name": "ریموت ایدی",
                "verbose_name_plural": "ریموت آیدی ها",
                "db_table": "remote_ids",
                "indexes": [
                    models.Index(
                        fields=["remote_id", "source_name"],
                        name="remote_ids_remote__702759_idx",
                    )
                ],
                "unique_together": {("series", "source_name")},
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tvdb_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="آیدی تی وی دی بی"
                    ),
                ),
                (
                    "character_name",
                    models.CharField(max_length=300, verbose_name="نام کاراکتر"),
                ),
                (
                    "character_image",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="تصویر کاراکتر"
                    ),
                ),
                (
                    "people_type",
                    models.CharField(
                        default="Actor", max_length=50, verbose_name="نوع شخص"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="series.person",
                        verbose_name="شخص",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="series.series",
                        verbose_name="سریال",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاراکتر",
                "verbose_name_plural": "کاراکتر ها",
                "db_table": "characters",
                "unique_together": {("series", "tvdb_id")},
            },
        ),
        migrations.CreateModel(
            name="SeriesGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="series.genre",
                        verbose_name="ژانر",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_genres",
                        to="series.series",
                        verbose_name="سریال",
                    ),
                ),
            ],
            options={
                "verbose_name": "ژانر سریال",
                "verbose_name_plural": "ژانر سریال ها",
                "db_table": "series_genres",
                "unique_together": {("series", "genre")},
            },
        ),
        migrations.CreateModel(
            name="TagOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tvdb_id", models.IntegerField(verbose_name="آیدی تی وی دی بی")),
                ("tag", models.IntegerField(verbose_name="تگ")),
                ("tag_name", models.CharField(max_length=200, verbose_name="نام تگ")),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_options",
                        to="series.series",
                        verbose_name="سریال",
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ اپشن",
                "verbose_name_plural": "تگ آپشن ها",
                "db_table": "tag_options",
                "unique_together": {("series", "tvdb_id")},
            },
        ),
    ]
