# Generated by Django 6.0.5 on 2026-08-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('series', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfWatch', models.CharField(choices=[('Series', 'سریال'), ('Movie', 'فیلم')], max_length=10, verbose_name='نوع محتوا')),
                ('status', models.CharField(choices=[('completed', 'تکمیل شده'), ('watching', 'در حال تماشا'), ('dropped', 'رها شده'), ('plan to watch', 'برنامه_تماشا')], max_length=20, verbose_name='وضعیت تماشا')),
                ('progress', models.IntegerField(blank=True, null=True, verbose_name='چقدر تماشا شده')),
                ('user_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='نمره کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('movies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movies', verbose_name='فیلم')),
                ('serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.series', verbose_name='سریال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ردیابی',
                'verbose_name_plural': 'ردیابی ها',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('typeOfWatch', 'Movie')), fields=('user', 'movies'), name='uniq_user_movie'), models.UniqueConstraint(condition=models.Q(('typeOfWatch', 'Series')), fields=('user', 'serial'), name='uniq_user_series')],
            },
        ),
    ]
