# Generated by Django 6.0.5 on 2026-08-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='مورد علاقه'),
        ),
    ]
