# Generated by Django 6.0.5 on 2026-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='filimo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='آدرس فیلیمو'),
        ),
        migrations.AddField(
            model_name='movies',
            name='namava',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='آدرس نماوا'),
        ),
    ]
